// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pcbdmqwjiecnnuyhkoup.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBjYmRtcXdqaWVjbm51eWhrb3VwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg2MzYzOTEsImV4cCI6MjA2NDIxMjM5MX0.lkcE5XFHkmH78ediDzsgnwZtA1_cm7fFi0otC-ogTGM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);